/* Minimal Profile A integration: no host application, just the license
 * lifecycle from the README. Not buildable standalone in this repository —
 * see examples/cmake-consumer for the intended consumption pattern once a
 * binary release exists.
 *
 * See also:
 *   updates/     — release checks and product notices
 *   activation/  — Profile B, activating from your own product
 *   offline/     — activating a machine with no network access
 */

#include <nexkeyruntime/nexkeyruntime.h>
#include <stdio.h>

/* Replace with a real blob generated by the MCNexus backoffice for your
 * tenant. Contains only a public keyring and a base URL -- no secret. */
static const char *NEXKEYRUNTIME_PRODUCT_DATA =
    "eyJmb3JtYXQiOiJuZXhrZXlydW50aW1lLXByb2R1Y3RkYXRhLXYxIiwi...";

int main(void) {
    NexKeyRuntimeLicenseHandle *license = nexkeyruntime_license_create();

    nexkeyruntime_license_set_product_data(license, NEXKEYRUNTIME_PRODUCT_DATA);
    nexkeyruntime_license_set_tenant_id(license, "your-tenant-id");
    nexkeyruntime_license_set_variant(license, "download:your-entitlement");
    nexkeyruntime_license_load_local(license);

    NexKeyRuntimeLicenseSnapshot snapshot;
    snapshot.struct_size = sizeof(snapshot);
    if (nexkeyruntime_license_get_snapshot(license, &snapshot) == NEXKEYRUNTIME_OK) {
        printf("license status: %d\n", (int)snapshot.status);
    }

    /* The one call safe to make from a render callback -- no I/O, a single
     * atomic read. */
    NexKeyRuntimeRenderDecision decision = nexkeyruntime_license_render_decision(license);
    printf("render decision: %s\n", decision == NEXKEYRUNTIME_RENDER_ALLOW ? "ALLOW" : "DENY");

    nexkeyruntime_license_destroy(license);
    return 0;
}
